// source: Tracer.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.google.protobuf.CreateFileData', null, global);
goog.exportSymbol('proto.google.protobuf.CursorChangeFileData', null, global);
goog.exportSymbol('proto.google.protobuf.DeleteFileData', null, global);
goog.exportSymbol('proto.google.protobuf.ModifyFileData', null, global);
goog.exportSymbol('proto.google.protobuf.RenameFileData', null, global);
goog.exportSymbol('proto.google.protobuf.SelectFileData', null, global);
goog.exportSymbol('proto.google.protobuf.TraceProject', null, global);
goog.exportSymbol('proto.google.protobuf.TraceTransaction', null, global);
goog.exportSymbol('proto.google.protobuf.TraceTransaction.DataCase', null, global);
goog.exportSymbol('proto.google.protobuf.TraceTransaction.TraceTransactionType', null, global);
goog.exportSymbol('proto.google.protobuf.TraceTransactionLog', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.protobuf.CreateFileData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.protobuf.CreateFileData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.protobuf.CreateFileData.displayName = 'proto.google.protobuf.CreateFileData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.protobuf.DeleteFileData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.protobuf.DeleteFileData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.protobuf.DeleteFileData.displayName = 'proto.google.protobuf.DeleteFileData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.protobuf.ModifyFileData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.protobuf.ModifyFileData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.protobuf.ModifyFileData.displayName = 'proto.google.protobuf.ModifyFileData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.protobuf.SelectFileData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.protobuf.SelectFileData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.protobuf.SelectFileData.displayName = 'proto.google.protobuf.SelectFileData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.protobuf.CursorChangeFileData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.protobuf.CursorChangeFileData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.protobuf.CursorChangeFileData.displayName = 'proto.google.protobuf.CursorChangeFileData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.protobuf.RenameFileData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.protobuf.RenameFileData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.protobuf.RenameFileData.displayName = 'proto.google.protobuf.RenameFileData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.protobuf.TraceTransaction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.google.protobuf.TraceTransaction.oneofGroups_);
};
goog.inherits(proto.google.protobuf.TraceTransaction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.protobuf.TraceTransaction.displayName = 'proto.google.protobuf.TraceTransaction';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.protobuf.TraceTransactionLog = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.protobuf.TraceTransactionLog.repeatedFields_, null);
};
goog.inherits(proto.google.protobuf.TraceTransactionLog, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.protobuf.TraceTransactionLog.displayName = 'proto.google.protobuf.TraceTransactionLog';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.protobuf.TraceProject = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.protobuf.TraceProject, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.protobuf.TraceProject.displayName = 'proto.google.protobuf.TraceProject';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.protobuf.CreateFileData.prototype.toObject = function(opt_includeInstance) {
  return proto.google.protobuf.CreateFileData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.protobuf.CreateFileData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.protobuf.CreateFileData.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.protobuf.CreateFileData}
 */
proto.google.protobuf.CreateFileData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.protobuf.CreateFileData;
  return proto.google.protobuf.CreateFileData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.protobuf.CreateFileData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.protobuf.CreateFileData}
 */
proto.google.protobuf.CreateFileData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.protobuf.CreateFileData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.protobuf.CreateFileData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.protobuf.CreateFileData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.protobuf.CreateFileData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.protobuf.DeleteFileData.prototype.toObject = function(opt_includeInstance) {
  return proto.google.protobuf.DeleteFileData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.protobuf.DeleteFileData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.protobuf.DeleteFileData.toObject = function(includeInstance, msg) {
  var f, obj = {
    previousData: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.protobuf.DeleteFileData}
 */
proto.google.protobuf.DeleteFileData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.protobuf.DeleteFileData;
  return proto.google.protobuf.DeleteFileData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.protobuf.DeleteFileData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.protobuf.DeleteFileData}
 */
proto.google.protobuf.DeleteFileData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPreviousData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.protobuf.DeleteFileData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.protobuf.DeleteFileData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.protobuf.DeleteFileData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.protobuf.DeleteFileData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPreviousData();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string previous_data = 1;
 * @return {string}
 */
proto.google.protobuf.DeleteFileData.prototype.getPreviousData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.protobuf.DeleteFileData} returns this
 */
proto.google.protobuf.DeleteFileData.prototype.setPreviousData = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.protobuf.ModifyFileData.prototype.toObject = function(opt_includeInstance) {
  return proto.google.protobuf.ModifyFileData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.protobuf.ModifyFileData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.protobuf.ModifyFileData.toObject = function(includeInstance, msg) {
  var f, obj = {
    offsetStart: jspb.Message.getFieldWithDefault(msg, 1, 0),
    offsetEnd: jspb.Message.getFieldWithDefault(msg, 2, 0),
    data: jspb.Message.getFieldWithDefault(msg, 3, ""),
    previousData: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.protobuf.ModifyFileData}
 */
proto.google.protobuf.ModifyFileData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.protobuf.ModifyFileData;
  return proto.google.protobuf.ModifyFileData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.protobuf.ModifyFileData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.protobuf.ModifyFileData}
 */
proto.google.protobuf.ModifyFileData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOffsetStart(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOffsetEnd(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setData(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPreviousData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.protobuf.ModifyFileData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.protobuf.ModifyFileData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.protobuf.ModifyFileData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.protobuf.ModifyFileData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOffsetStart();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getOffsetEnd();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getData();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPreviousData();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional uint32 offset_start = 1;
 * @return {number}
 */
proto.google.protobuf.ModifyFileData.prototype.getOffsetStart = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.protobuf.ModifyFileData} returns this
 */
proto.google.protobuf.ModifyFileData.prototype.setOffsetStart = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 offset_end = 2;
 * @return {number}
 */
proto.google.protobuf.ModifyFileData.prototype.getOffsetEnd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.protobuf.ModifyFileData} returns this
 */
proto.google.protobuf.ModifyFileData.prototype.setOffsetEnd = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string data = 3;
 * @return {string}
 */
proto.google.protobuf.ModifyFileData.prototype.getData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.protobuf.ModifyFileData} returns this
 */
proto.google.protobuf.ModifyFileData.prototype.setData = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string previous_data = 4;
 * @return {string}
 */
proto.google.protobuf.ModifyFileData.prototype.getPreviousData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.protobuf.ModifyFileData} returns this
 */
proto.google.protobuf.ModifyFileData.prototype.setPreviousData = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.protobuf.SelectFileData.prototype.toObject = function(opt_includeInstance) {
  return proto.google.protobuf.SelectFileData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.protobuf.SelectFileData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.protobuf.SelectFileData.toObject = function(includeInstance, msg) {
  var f, obj = {
    newFilePath: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.protobuf.SelectFileData}
 */
proto.google.protobuf.SelectFileData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.protobuf.SelectFileData;
  return proto.google.protobuf.SelectFileData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.protobuf.SelectFileData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.protobuf.SelectFileData}
 */
proto.google.protobuf.SelectFileData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNewFilePath(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.protobuf.SelectFileData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.protobuf.SelectFileData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.protobuf.SelectFileData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.protobuf.SelectFileData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNewFilePath();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string new_file_path = 1;
 * @return {string}
 */
proto.google.protobuf.SelectFileData.prototype.getNewFilePath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.protobuf.SelectFileData} returns this
 */
proto.google.protobuf.SelectFileData.prototype.setNewFilePath = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.protobuf.CursorChangeFileData.prototype.toObject = function(opt_includeInstance) {
  return proto.google.protobuf.CursorChangeFileData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.protobuf.CursorChangeFileData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.protobuf.CursorChangeFileData.toObject = function(includeInstance, msg) {
  var f, obj = {
    offsetStart: jspb.Message.getFieldWithDefault(msg, 1, 0),
    offsetEnd: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.protobuf.CursorChangeFileData}
 */
proto.google.protobuf.CursorChangeFileData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.protobuf.CursorChangeFileData;
  return proto.google.protobuf.CursorChangeFileData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.protobuf.CursorChangeFileData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.protobuf.CursorChangeFileData}
 */
proto.google.protobuf.CursorChangeFileData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOffsetStart(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOffsetEnd(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.protobuf.CursorChangeFileData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.protobuf.CursorChangeFileData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.protobuf.CursorChangeFileData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.protobuf.CursorChangeFileData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOffsetStart();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getOffsetEnd();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
};


/**
 * optional uint32 offset_start = 1;
 * @return {number}
 */
proto.google.protobuf.CursorChangeFileData.prototype.getOffsetStart = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.protobuf.CursorChangeFileData} returns this
 */
proto.google.protobuf.CursorChangeFileData.prototype.setOffsetStart = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 offset_end = 2;
 * @return {number}
 */
proto.google.protobuf.CursorChangeFileData.prototype.getOffsetEnd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.protobuf.CursorChangeFileData} returns this
 */
proto.google.protobuf.CursorChangeFileData.prototype.setOffsetEnd = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.protobuf.RenameFileData.prototype.toObject = function(opt_includeInstance) {
  return proto.google.protobuf.RenameFileData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.protobuf.RenameFileData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.protobuf.RenameFileData.toObject = function(includeInstance, msg) {
  var f, obj = {
    newFilePath: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.protobuf.RenameFileData}
 */
proto.google.protobuf.RenameFileData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.protobuf.RenameFileData;
  return proto.google.protobuf.RenameFileData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.protobuf.RenameFileData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.protobuf.RenameFileData}
 */
proto.google.protobuf.RenameFileData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNewFilePath(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.protobuf.RenameFileData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.protobuf.RenameFileData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.protobuf.RenameFileData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.protobuf.RenameFileData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNewFilePath();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string new_file_path = 1;
 * @return {string}
 */
proto.google.protobuf.RenameFileData.prototype.getNewFilePath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.protobuf.RenameFileData} returns this
 */
proto.google.protobuf.RenameFileData.prototype.setNewFilePath = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.google.protobuf.TraceTransaction.oneofGroups_ = [[4,5,6,7,8,9]];

/**
 * @enum {number}
 */
proto.google.protobuf.TraceTransaction.DataCase = {
  DATA_NOT_SET: 0,
  CREATE_FILE: 4,
  DELETE_FILE: 5,
  MODIFY_FILE: 6,
  SELECT_FILE: 7,
  CURSOR_FILE: 8,
  RENAME_FILE: 9
};

/**
 * @return {proto.google.protobuf.TraceTransaction.DataCase}
 */
proto.google.protobuf.TraceTransaction.prototype.getDataCase = function() {
  return /** @type {proto.google.protobuf.TraceTransaction.DataCase} */(jspb.Message.computeOneofCase(this, proto.google.protobuf.TraceTransaction.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.protobuf.TraceTransaction.prototype.toObject = function(opt_includeInstance) {
  return proto.google.protobuf.TraceTransaction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.protobuf.TraceTransaction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.protobuf.TraceTransaction.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    timeOffsetMs: jspb.Message.getFieldWithDefault(msg, 2, 0),
    filePath: jspb.Message.getFieldWithDefault(msg, 3, ""),
    createFile: (f = msg.getCreateFile()) && proto.google.protobuf.CreateFileData.toObject(includeInstance, f),
    deleteFile: (f = msg.getDeleteFile()) && proto.google.protobuf.DeleteFileData.toObject(includeInstance, f),
    modifyFile: (f = msg.getModifyFile()) && proto.google.protobuf.ModifyFileData.toObject(includeInstance, f),
    selectFile: (f = msg.getSelectFile()) && proto.google.protobuf.SelectFileData.toObject(includeInstance, f),
    cursorFile: (f = msg.getCursorFile()) && proto.google.protobuf.CursorChangeFileData.toObject(includeInstance, f),
    renameFile: (f = msg.getRenameFile()) && proto.google.protobuf.RenameFileData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.protobuf.TraceTransaction}
 */
proto.google.protobuf.TraceTransaction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.protobuf.TraceTransaction;
  return proto.google.protobuf.TraceTransaction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.protobuf.TraceTransaction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.protobuf.TraceTransaction}
 */
proto.google.protobuf.TraceTransaction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.google.protobuf.TraceTransaction.TraceTransactionType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTimeOffsetMs(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilePath(value);
      break;
    case 4:
      var value = new proto.google.protobuf.CreateFileData;
      reader.readMessage(value,proto.google.protobuf.CreateFileData.deserializeBinaryFromReader);
      msg.setCreateFile(value);
      break;
    case 5:
      var value = new proto.google.protobuf.DeleteFileData;
      reader.readMessage(value,proto.google.protobuf.DeleteFileData.deserializeBinaryFromReader);
      msg.setDeleteFile(value);
      break;
    case 6:
      var value = new proto.google.protobuf.ModifyFileData;
      reader.readMessage(value,proto.google.protobuf.ModifyFileData.deserializeBinaryFromReader);
      msg.setModifyFile(value);
      break;
    case 7:
      var value = new proto.google.protobuf.SelectFileData;
      reader.readMessage(value,proto.google.protobuf.SelectFileData.deserializeBinaryFromReader);
      msg.setSelectFile(value);
      break;
    case 8:
      var value = new proto.google.protobuf.CursorChangeFileData;
      reader.readMessage(value,proto.google.protobuf.CursorChangeFileData.deserializeBinaryFromReader);
      msg.setCursorFile(value);
      break;
    case 9:
      var value = new proto.google.protobuf.RenameFileData;
      reader.readMessage(value,proto.google.protobuf.RenameFileData.deserializeBinaryFromReader);
      msg.setRenameFile(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.protobuf.TraceTransaction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.protobuf.TraceTransaction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.protobuf.TraceTransaction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.protobuf.TraceTransaction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getTimeOffsetMs();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getFilePath();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCreateFile();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.google.protobuf.CreateFileData.serializeBinaryToWriter
    );
  }
  f = message.getDeleteFile();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.google.protobuf.DeleteFileData.serializeBinaryToWriter
    );
  }
  f = message.getModifyFile();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.google.protobuf.ModifyFileData.serializeBinaryToWriter
    );
  }
  f = message.getSelectFile();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.google.protobuf.SelectFileData.serializeBinaryToWriter
    );
  }
  f = message.getCursorFile();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.google.protobuf.CursorChangeFileData.serializeBinaryToWriter
    );
  }
  f = message.getRenameFile();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.google.protobuf.RenameFileData.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.google.protobuf.TraceTransaction.TraceTransactionType = {
  CREATEFILE: 0,
  DELETEFILE: 1,
  MODIFYFILE: 2,
  SELECTFILE: 3,
  CURSORFILE: 4,
  RENAMEFILE: 5
};

/**
 * optional TraceTransactionType type = 1;
 * @return {!proto.google.protobuf.TraceTransaction.TraceTransactionType}
 */
proto.google.protobuf.TraceTransaction.prototype.getType = function() {
  return /** @type {!proto.google.protobuf.TraceTransaction.TraceTransactionType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.google.protobuf.TraceTransaction.TraceTransactionType} value
 * @return {!proto.google.protobuf.TraceTransaction} returns this
 */
proto.google.protobuf.TraceTransaction.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional uint32 time_offset_ms = 2;
 * @return {number}
 */
proto.google.protobuf.TraceTransaction.prototype.getTimeOffsetMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.protobuf.TraceTransaction} returns this
 */
proto.google.protobuf.TraceTransaction.prototype.setTimeOffsetMs = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string file_path = 3;
 * @return {string}
 */
proto.google.protobuf.TraceTransaction.prototype.getFilePath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.protobuf.TraceTransaction} returns this
 */
proto.google.protobuf.TraceTransaction.prototype.setFilePath = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional CreateFileData create_file = 4;
 * @return {?proto.google.protobuf.CreateFileData}
 */
proto.google.protobuf.TraceTransaction.prototype.getCreateFile = function() {
  return /** @type{?proto.google.protobuf.CreateFileData} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.CreateFileData, 4));
};


/**
 * @param {?proto.google.protobuf.CreateFileData|undefined} value
 * @return {!proto.google.protobuf.TraceTransaction} returns this
*/
proto.google.protobuf.TraceTransaction.prototype.setCreateFile = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.google.protobuf.TraceTransaction.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.protobuf.TraceTransaction} returns this
 */
proto.google.protobuf.TraceTransaction.prototype.clearCreateFile = function() {
  return this.setCreateFile(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.protobuf.TraceTransaction.prototype.hasCreateFile = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional DeleteFileData delete_file = 5;
 * @return {?proto.google.protobuf.DeleteFileData}
 */
proto.google.protobuf.TraceTransaction.prototype.getDeleteFile = function() {
  return /** @type{?proto.google.protobuf.DeleteFileData} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.DeleteFileData, 5));
};


/**
 * @param {?proto.google.protobuf.DeleteFileData|undefined} value
 * @return {!proto.google.protobuf.TraceTransaction} returns this
*/
proto.google.protobuf.TraceTransaction.prototype.setDeleteFile = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.google.protobuf.TraceTransaction.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.protobuf.TraceTransaction} returns this
 */
proto.google.protobuf.TraceTransaction.prototype.clearDeleteFile = function() {
  return this.setDeleteFile(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.protobuf.TraceTransaction.prototype.hasDeleteFile = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional ModifyFileData modify_file = 6;
 * @return {?proto.google.protobuf.ModifyFileData}
 */
proto.google.protobuf.TraceTransaction.prototype.getModifyFile = function() {
  return /** @type{?proto.google.protobuf.ModifyFileData} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.ModifyFileData, 6));
};


/**
 * @param {?proto.google.protobuf.ModifyFileData|undefined} value
 * @return {!proto.google.protobuf.TraceTransaction} returns this
*/
proto.google.protobuf.TraceTransaction.prototype.setModifyFile = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.google.protobuf.TraceTransaction.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.protobuf.TraceTransaction} returns this
 */
proto.google.protobuf.TraceTransaction.prototype.clearModifyFile = function() {
  return this.setModifyFile(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.protobuf.TraceTransaction.prototype.hasModifyFile = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional SelectFileData select_file = 7;
 * @return {?proto.google.protobuf.SelectFileData}
 */
proto.google.protobuf.TraceTransaction.prototype.getSelectFile = function() {
  return /** @type{?proto.google.protobuf.SelectFileData} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.SelectFileData, 7));
};


/**
 * @param {?proto.google.protobuf.SelectFileData|undefined} value
 * @return {!proto.google.protobuf.TraceTransaction} returns this
*/
proto.google.protobuf.TraceTransaction.prototype.setSelectFile = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.google.protobuf.TraceTransaction.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.protobuf.TraceTransaction} returns this
 */
proto.google.protobuf.TraceTransaction.prototype.clearSelectFile = function() {
  return this.setSelectFile(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.protobuf.TraceTransaction.prototype.hasSelectFile = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional CursorChangeFileData cursor_file = 8;
 * @return {?proto.google.protobuf.CursorChangeFileData}
 */
proto.google.protobuf.TraceTransaction.prototype.getCursorFile = function() {
  return /** @type{?proto.google.protobuf.CursorChangeFileData} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.CursorChangeFileData, 8));
};


/**
 * @param {?proto.google.protobuf.CursorChangeFileData|undefined} value
 * @return {!proto.google.protobuf.TraceTransaction} returns this
*/
proto.google.protobuf.TraceTransaction.prototype.setCursorFile = function(value) {
  return jspb.Message.setOneofWrapperField(this, 8, proto.google.protobuf.TraceTransaction.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.protobuf.TraceTransaction} returns this
 */
proto.google.protobuf.TraceTransaction.prototype.clearCursorFile = function() {
  return this.setCursorFile(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.protobuf.TraceTransaction.prototype.hasCursorFile = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional RenameFileData rename_file = 9;
 * @return {?proto.google.protobuf.RenameFileData}
 */
proto.google.protobuf.TraceTransaction.prototype.getRenameFile = function() {
  return /** @type{?proto.google.protobuf.RenameFileData} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.RenameFileData, 9));
};


/**
 * @param {?proto.google.protobuf.RenameFileData|undefined} value
 * @return {!proto.google.protobuf.TraceTransaction} returns this
*/
proto.google.protobuf.TraceTransaction.prototype.setRenameFile = function(value) {
  return jspb.Message.setOneofWrapperField(this, 9, proto.google.protobuf.TraceTransaction.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.protobuf.TraceTransaction} returns this
 */
proto.google.protobuf.TraceTransaction.prototype.clearRenameFile = function() {
  return this.setRenameFile(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.protobuf.TraceTransaction.prototype.hasRenameFile = function() {
  return jspb.Message.getField(this, 9) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.protobuf.TraceTransactionLog.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.protobuf.TraceTransactionLog.prototype.toObject = function(opt_includeInstance) {
  return proto.google.protobuf.TraceTransactionLog.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.protobuf.TraceTransactionLog} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.protobuf.TraceTransactionLog.toObject = function(includeInstance, msg) {
  var f, obj = {
    partition: jspb.Message.getFieldWithDefault(msg, 1, 0),
    transactionsList: jspb.Message.toObjectList(msg.getTransactionsList(),
    proto.google.protobuf.TraceTransaction.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.protobuf.TraceTransactionLog}
 */
proto.google.protobuf.TraceTransactionLog.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.protobuf.TraceTransactionLog;
  return proto.google.protobuf.TraceTransactionLog.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.protobuf.TraceTransactionLog} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.protobuf.TraceTransactionLog}
 */
proto.google.protobuf.TraceTransactionLog.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPartition(value);
      break;
    case 2:
      var value = new proto.google.protobuf.TraceTransaction;
      reader.readMessage(value,proto.google.protobuf.TraceTransaction.deserializeBinaryFromReader);
      msg.addTransactions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.protobuf.TraceTransactionLog.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.protobuf.TraceTransactionLog.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.protobuf.TraceTransactionLog} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.protobuf.TraceTransactionLog.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPartition();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getTransactionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.google.protobuf.TraceTransaction.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 partition = 1;
 * @return {number}
 */
proto.google.protobuf.TraceTransactionLog.prototype.getPartition = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.protobuf.TraceTransactionLog} returns this
 */
proto.google.protobuf.TraceTransactionLog.prototype.setPartition = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated TraceTransaction transactions = 2;
 * @return {!Array<!proto.google.protobuf.TraceTransaction>}
 */
proto.google.protobuf.TraceTransactionLog.prototype.getTransactionsList = function() {
  return /** @type{!Array<!proto.google.protobuf.TraceTransaction>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.protobuf.TraceTransaction, 2));
};


/**
 * @param {!Array<!proto.google.protobuf.TraceTransaction>} value
 * @return {!proto.google.protobuf.TraceTransactionLog} returns this
*/
proto.google.protobuf.TraceTransactionLog.prototype.setTransactionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.google.protobuf.TraceTransaction=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.protobuf.TraceTransaction}
 */
proto.google.protobuf.TraceTransactionLog.prototype.addTransactions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.google.protobuf.TraceTransaction, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.protobuf.TraceTransactionLog} returns this
 */
proto.google.protobuf.TraceTransactionLog.prototype.clearTransactionsList = function() {
  return this.setTransactionsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.protobuf.TraceProject.prototype.toObject = function(opt_includeInstance) {
  return proto.google.protobuf.TraceProject.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.protobuf.TraceProject} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.protobuf.TraceProject.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    duration: jspb.Message.getFieldWithDefault(msg, 2, 0),
    partitionSize: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.protobuf.TraceProject}
 */
proto.google.protobuf.TraceProject.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.protobuf.TraceProject;
  return proto.google.protobuf.TraceProject.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.protobuf.TraceProject} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.protobuf.TraceProject}
 */
proto.google.protobuf.TraceProject.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDuration(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPartitionSize(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.protobuf.TraceProject.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.protobuf.TraceProject.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.protobuf.TraceProject} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.protobuf.TraceProject.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDuration();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getPartitionSize();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.google.protobuf.TraceProject.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.protobuf.TraceProject} returns this
 */
proto.google.protobuf.TraceProject.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint32 duration = 2;
 * @return {number}
 */
proto.google.protobuf.TraceProject.prototype.getDuration = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.protobuf.TraceProject} returns this
 */
proto.google.protobuf.TraceProject.prototype.setDuration = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 partition_size = 3;
 * @return {number}
 */
proto.google.protobuf.TraceProject.prototype.getPartitionSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.protobuf.TraceProject} returns this
 */
proto.google.protobuf.TraceProject.prototype.setPartitionSize = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


goog.object.extend(exports, proto.google.protobuf);
